server:
  port: 8301
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fymeven/efast
          username: fymeven
          password: evenspike233
          search-paths: config
      label: master