server:
  port: 8301
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fymeven/efast.git
          username: fymeven
          password: evenspike233