###################### server ######################
server:
  port: 8801
  servlet:
    session:
      cookie:
        name: oauth_cas_jid
    context-path: /security-cas-server
###################### eureka ######################
eureka:
    instance:
      ip-address: 127.0.0.1
      prefer-ip-address: true
    client:
      service-url:
        defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka,http://127.0.0.1:8763/eureka
###################### spring ######################
spring:
  application:
    name: security-cas-server
  ###################### datasource ######################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.107.151.224:3306/efast-cas
    username: even
    password: even@mysql_224
    driver-class-name: com.mysql.jdbc.Driver
  ###################### redis ######################
  redis:
    host: 47.107.151.224
    port: 6379
    password: even@redis_224
###################### swagger ######################
swagger:
  enabled: true
###################### log ######################
logging:
  level:
    org.springframework.security: debug
    cn._51even.efast.security_cas_server: debug