###################### server ######################
server:
  port: 8080
spring:
  application:
    name: gateway-proxy
  redis:
    host: 47.107.151.224
    port: 6379
    password: even@redis_224
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka,http://127.0.0.1:8763/eureka
feign:
  hystrix:
    enabled: true