###################### server ######################
server:
  servlet:
    context-path: /efast-web
  port: 8088
###################### spring ######################
spring:
  application:
    name: efast-web
  ###################### datasource ######################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.107.151.224:3306/even
    username: even
    password: even@mysql_224
    driver-class-name: com.mysql.jdbc.Driver
  ###################### redis ######################
  redis:
    host: 47.107.151.224
    port: 6379
    password: even@redis_224
  ###################### thymeleaf ######################
  thymeleaf:
    cache: false
    encoding: UTF-8
  ###################### security ######################
  security:
    oauth2:
      client:
        registration:
          github:
            provider: github
            clientId: 1aa86dcdb5a67d97770d
            clientSecret: e3410e9972b641e505e20368f95ad9d215444916
          efast:
            clientId: client1
            clientSecret: e10adc3949ba59abbe56e057f20f883e
            redirectUriTemplate: http://127.0.0.1:8088/efast-web/login/oauth/code/efast
            scope: login
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: basic
        provider:
          efast:
            tokenUri: http://127.0.0.1:8801/security-cas-server/oauth/token
            authorizationUri: http://127.0.0.1:8801/security-cas-server/oauth/authorize
            userInfoUri: http://127.0.0.1:8801/security-cas-server/oauth/user
###################### swagger ######################
swagger:
  enabled: true