server:
  port: 8401
spring:
  application:
    name: cloud-register-client
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8501/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false