###################### server ######################
server:
  port: 80
spring:
  application:
    name: cloud-gateway-proxy
  redis:
    host: 47.107.151.224
    port: 6379
    password: even@redis_224
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8501/eureka,http://127.0.0.1:8502/eureka,http://127.0.0.1:8503/eureka
feign:
  hystrix:
    enabled: true