server:
  port: 8503
spring:
  application:
    name: cloud-register-server
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8501/eureka,http://127.0.0.1:8502/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
