###################### server ######################
server:
  port: 8308
###################### eureka ######################
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8501/eureka,http://127.0.0.1:8502/eureka,http://127.0.0.1:8503/eureka
###################### actuator ######################
management:
  endpoints:
    web:
      exposure:
        include: "*"
###################### spring ######################
spring:
  application:
    name: fastdfs-file-server
###################### swagger ######################
swagger:
  enabled: true
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  web-server-url:
    47.107.151.224:8388
  tracker-list:
    47.107.151.224:22122